# -*- coding: utf-8 -*-
"""EXNO:05 Data visualization Using Matplotlib

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2pYYhrUUGikYUnn1k0s5p_wtwYUshVf

**Data visualization Using Matplotlib**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [3, 6, 2, 7, 1]

# CREATE A LINE GRAPH FOR X AND Y AND LABEL X axis and Y Axis and create a legend

# line 1 points
x1 = [1,2,3]
y1 = [2,4,1]
x2 = [1,2,3]
y2 = [4,1,3]

# plot line 1 and line 2 points in same graph and include the necessary parameters

# plot the points in the above graph

# Creating some random data
x = [1, 2, 3, 4, 5]
y1 = [10, 12, 14, 16, 18]
y2 = [5, 7, 9, 11, 13]
y3 = [2, 4, 6, 8, 10]

x_values = [0,1,2,3,4,5]
y_values = [0,1,4,9,16,25]

# implement line graph using fill between option

from scipy.interpolate import make_interp_spline
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([2, 4, 5, 7, 8, 8, 9, 10, 11, 12])

# interpolate data using cubic spline

"""**BAR GRAPH**"""

values = [5, 6, 3, 7, 2]
names  = ["A", "B", "C", "D", "E"]

# Create bar graph using the above two variables and include the necessary parameters

c1 =['red', 'green']
c2 =['b', 'g'] # we can use this for color
# plot a bar chart

df = sns.load_dataset("tips")

df

plt.figure(figsize=(8, 6))
p1 = plt.bar(avg_total_bill.index, avg_total_bill, label='Total Bill')
p2 = plt.bar(avg_tip.index, avg_tip, bottom=avg_total_bill, label='Tip')
# Set the labels and title
plt.xlabel('Day of the Week')
plt.ylabel('Amount')
plt.title('Average Total Bill and Tip by Day')
plt.legend()

"""**SCATTER PLOT**"""

x_values = [0,1,2,3,4,5]
y_values = [0,1,4,9,16,25]

# CREATE A SCATTER PLOT FOR X_VALUES AND Y_VALUES

# x-axis values
x = [1,2,3,4,5,6,7,8,9,10]
# y-axis values
y = [2,4,5,7,6,8,9,11,12,12]

# plot the above points x and y in scatter plot Using the parmeters label= "stars", color="green", marker="*", s=30

# set x-axis label and y axis label

# set the title and legend of the graph

"""**Pie-chart**"""

# defining labels
activities = ['eat', 'sleep', 'work', 'play']
# portion covered by each label
slices = [3, 7, 8, 6]
# color for each label
colors = ['r', 'y', 'g', 'b']

# plot the pie chart using above parameters